name: Branch Handler

on:
  workflow_dispatch:
    inputs:
      branch_type:
        description: Type of branch (hotfix or sprint)
        required: true
        type: choice
        options:
          - hotfix
          - sprint
      tag_or_sprint:
        description: Version number or Sprint number
        required: false
      action:
        description: Action to perform
        required: true
        default: review
        type: choice
        options:
          - review
          - keep
          - delete
      confirm_delete:
        description: Confirm deletion
        required: false
        default: NO
        type: choice
        options:
          - NO
          - YES

jobs:
  handle-branches:
    runs-on: storelink
    outputs:
      hotfix_exists: ${{ steps.filter_branches.outputs.hotfix_exists }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch branches
        id: fetch_branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash scripts/fetch_branches.sh

      - name: Filter branches
        id: filter_branches
        env:
          BRANCH_TYPE: ${{ github.event.inputs.branch_type }}
          TAG_OR_SPRINT: ${{ github.event.inputs.tag_or_sprint }}
        run: bash scripts/filter_branches.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: branch-handler-output
          path: branch-handler-artifact.log

      - name: Confirm or exit on review
        if: ${{ github.event.inputs.action == 'review' }}
        run: echo "Review complete. No action taken."

      - name: Confirm delete
        if: ${{ github.event.inputs.action == 'delete' }}
        env:
          CONFIRM_DELETE: ${{ github.event.inputs.confirm_delete }}
        run: bash scripts/confirm_delete.sh

      - name: Delete branches
        if: ${{ github.event.inputs.action == 'delete' && github.event.inputs.confirm_delete == 'YES' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash scripts/delete_branches.sh

      - name: Keep branches (no-op)
        if: ${{ github.event.inputs.action == 'keep' }}
        run: bash scripts/keep_branches.sh
