name: New Branch Handler
run-name: >
  ${{ github.actor }} triggered ${{ github.event.inputs.action }} for
  ${{ github.event.inputs.branch_type }}-${{ github.event.inputs.tag_or_sprint }}

on:
  workflow_dispatch:
    inputs:
      branch_type:
        description: Type of branch (hotfix or sprint)
        required: true
        type: choice
        options:
          - hotfix
          - sprint
      tag_or_sprint:
        description: Version number or Sprint number
        required: false
      action:
        description: Action to perform
        required: true
        default: review
        type: choice
        options:
          - review
          - keep
          - delete
      confirm_deletion:
        description: Confirm deletion
        required: false
        default: NO
        type: choice
        options:
          - NO
          - YES

jobs:
  handle-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all branches
        id: fetch_branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: bash scripts/fetch_branches.sh

      - name: Filter branches and generate artifacts
        id: filter_branches
        run: bash scripts/filter_branches.sh "${{ github.event.inputs.branch_type }}" "${{ github.event.inputs.tag_or_sprint }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: branch-handler-output
          path: branch-handler-artifact.log

      - name: Stop if action is review
        if: ${{ github.event.inputs.action == 'review' }}
        run: |
          echo "Branch list uploaded for review. No action will be taken."
          echo "To take action, re-run the workflow and choose 'keep' or 'delete'."
          exit 0

      - name: Confirm deletion
        if: ${{ github.event.inputs.action == 'delete' }}
        run: |
          echo "User input: '${{ github.event.inputs.confirm_deletion }}'"
          if [[ "${{ github.event.inputs.confirm_deletion }}" == "YES" ]]; then
            echo "Confirmed deletion."
            bash scripts/confirm_delete.sh
          else
            echo "Deletion not confirmed. Skipping confirmation step."
          fi

      - name: Debug confirm deletion and action
        run: |
          echo "Action: '${{ github.event.inputs.action }}'"
          echo "Confirm Delete: '${{ github.event.inputs.confirm_deletion }}'"

      - name: Delete branches
        if: ${{ github.event.inputs.action == 'delete' && format('{0}', github.event.inputs.confirm_deletion) == 'YES' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: bash scripts/delete_branches.sh

      - name: Keep branches (no action)
        if: ${{ github.event.inputs.action == 'keep' }}
        run: bash scripts/keep_branches.sh
